### ISSUE TITLE
No Issue, but can I buy you a coffee?

### ISSUE THREAD

**Issue by OleSint** [hurzhurz/psa-token-helper#1]
Found no messaging possibility, so sorry for posting here.
This tool helped me saving years of my life for nut struggeling to find the refresh token anymore.
Are you at buymeacoffe or something?

**Comment by hurzhurz** [comment]
I'm very happy to hear that this thing is helpful to you :)

No, I'm not on buymeacoffee or similar sites, at least not as creator, but I appreciate you were asking!
